name = "LGravity"
uuid = "1b53e84f-5fe9-4c84-ab3c-08488970ec2d"
authors = ["Alex Tantos"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
